const song_database = {
    Scarlet_Devil:[ //红魔乡
        { name: '赤より紅い夢', file: 'audio/Scarlet_Devil/title.mid' },
        { name: 'ほおずきみたいに紅い魂', file: 'audio/Scarlet_Devil/stage1_mid.mid' },
        { name: '妖魔夜行', file: 'audio/Scarlet_Devil/stage1_boss.mid' },
        { name: 'ルーネイトエルフ', file: 'audio/Scarlet_Devil/stage2_mid.mid' },
        { name: 'おてんば恋娘', file: 'audio/Scarlet_Devil/stage2_boss.mid' },
        { name: '上海紅茶館 ～ Chinese Tea', file: 'audio/Scarlet_Devil/stage3_mid.mid' },
        { name: '明治十七年の上海アリス', file: 'audio/Scarlet_Devil/stage3_boss.mid' },
        { name: 'ヴワル魔法図書館', file: 'audio/Scarlet_Devil/stage4_mid.mid' },
        { name: 'ラクトガール ～ 少女密室', file: 'audio/Scarlet_Devil/stage4_boss.mid' },
        { name: 'メイドと血の懐中時計', file: 'audio/Scarlet_Devil/stage5_mid.mid' },
        { name: '月時計 ～ ルナ・ダイアル', file: 'audio/Scarlet_Devil/stage5_boss.mid' },
        { name: 'ツェペシュの幼き末裔', file: 'audio/Scarlet_Devil/stage6_mid.mid' },
        { name: '亡き王女の為のセプテット', file: 'audio/Scarlet_Devil/stage6_boss.mid' },
        { name: '魔法少女達の百年祭', file: 'audio/Scarlet_Devil/stageEX_mid.mid' },
        { name: 'U.N.オーエンは彼女なのか？', file: 'audio/Scarlet_Devil/stageEX_boss.mid' },
        { name: '紅より儚い永遠', file: 'audio/Scarlet_Devil/ending.mid' },
        { name: '紅楼 ～ Eastern Dream...', file: 'audio/Scarlet_Devil/staff_roll.mid' }
    ],
    Perfect_Cherry: [  // 妖妖梦
        { name: '妖々夢 ～ Snow or Cherry', file: 'audio/Perfect_Cherry/title.mid' },
        { name: '無何有の郷 ～ Deep Mountain', file: 'audio/Perfect_Cherry/stage1_mid.mid' },
        { name: 'クリスタライズシルバー', file: 'audio/Perfect_Cherry/stage1_boss.mid' },
        { name: '遠野幻想物語', file: 'audio/Perfect_Cherry/stage2_mid.mid' },
        { name: 'ティアオイエツォン (withered leaf)', file: 'audio/Perfect_Cherry/stage2_boss.mid' },
        { name: 'ブクレシュティの人形師', file: 'audio/Perfect_Cherry/stage3_mid.mid' },
        { name: '人形裁判 ～ 人の形弄びし少女', file: 'audio/Perfect_Cherry/stage3_boss.mid' },
        { name: '天空の花の都', file: 'audio/Perfect_Cherry/stage4_mid.mid' },
        { name: '幽霊楽団 ～ Phantom Ensemble', file: 'audio/Perfect_Cherry/stage4_boss.mid' },
        { name: '東方妖々夢 ～ Ancient Temple', file: 'audio/Perfect_Cherry/stage5_mid.mid' },
        { name: '広有射怪鳥事 ～ Till When?', file: 'audio/Perfect_Cherry/stage5_boss.mid' },
        { name: 'アルティメットトゥルース', file: 'audio/Perfect_Cherry/stage6_mid.mid' },
        { name: '幽雅に咲かせ、墨染の桜 (Border of Life)', file: 'audio/Perfect_Cherry/stage6_bossA.mid' },
        { name: 'ボーダーオブライフ', file: 'audio/Perfect_Cherry/stage6_bossB.mid' },
        { name: '妖々跋扈', file: 'audio/Perfect_Cherry/stageEX_mid.mid' },
        { name: '少女幻葬 ～ Necro-Fantasy', file: 'audio/Perfect_Cherry/stageEX_boss.mid' },
        { name: '妖々跋扈 ～ Who done it!', file: 'audio/Perfect_Cherry/stagePH_mid.mid' },
        { name: 'ネクロファンタジア', file: 'audio/Perfect_Cherry/stagePH_boss.mid' },
        { name: '春風の夢', file: 'audio/Perfect_Cherry/ending.mid' },
        { name: 'さくらさくら ～ Japanize Dream...', file: 'audio/Perfect_Cherry/staff_roll.mid' }
    ],
    Imperishable_Night: [ // 永夜抄
        { name: '永夜抄 ～ Eastern Night', file: 'audio/Imperishable_Night/title.mid' },
        { name: '幻視の夜 ～ Ghostly Eyes', file: 'audio/Imperishable_Night/stage1_mid.mid' },
        { name: '蠢々秋月 ～ Mooned Insect',file:'audio/Imperishable_Night/stage1_boss.mid'},
        { name: '夜雀の歌声 ～ Night Bird',file:'audio/Imperishable_Night/stage2_mid.mid'},
        { name: 'もう歌しか聞こえない',file:'audio/Imperishable_Night/stage2_boss.mid'},
        { name: 'プレインエイジア',file:'audio/Imperishable_Night/stage3_boss.mid'},
        { name: '懐かしき東方の血 ～ Old World',file:'audio/Imperishable_Night/stage3_mid.mid'},
        { name: '永夜の報い ～ Imperishable Night',file:'audio/Imperishable_Night/stage4_mid.mid'},
        { name: '少女綺想曲 ～ Dream Battle',file:'audio/Imperishable_Night/stage4_boss_reimu.mid'},
        { name: '恋色マスタースパーク',file:'audio/Imperishable_Night/stage4_boss_marisa.mid'},
        { name: 'シンデレラケージ ～ Kagome-Kagome',file:'audio/Imperishable_Night/stage5_mid.mid'},
        { name: '狂気の瞳 ～ Invisible Full Moon',file:'audio/Imperishable_Night/stage5_boss.mid'},
        { name: 'ヴォヤージュ1969',file:'audio/Imperishable_Night/stage6_mid.mid'},
        { name: '千年幻想郷 ～ History of the Moon',file:'audio/Imperishable_Night/stage6A_boss.mid'},
        { name: '竹取飛翔 ～ Lunatic Princess', file: 'audio/Imperishable_Night/stage6B_boss.mid' },
        { name: 'ヴォヤージュ1970',file:'audio/Imperishable_Night/final_spell.mid'},
        { name:'エクステンドアッシュ ～ 蓬莱人',file:'audio/Imperishable_Night/stageEX_mid.mid'},
        { name:'月まで届け、不死の煙',file:'audio/Imperishable_Night/stageEX_boss.mid'},
        { name:'月見草',file:'audio/Imperishable_Night/ending.mid'},
        { name:'Eternal Dream ～ 幽玄の槭樹',file:'audio/Imperishable_Night/staff_roll.mid'},
        { name:'東方妖怪小町',file:'audio/Imperishable_Night/last_word.mid'}
    ],
    Responsive_to_Prayers:[
        {name :'A Sacred Lot',file:'audio/Responsive_to_Prayers/track1.mid'},
        {name :'永遠の巫女',file:'audio/Responsive_to_Prayers/track2.mid'},
        {name :'The Positive and Negative',file:'audio/Responsive_to_Prayers/track3.mid'},
        {name :'Highly Responsive to Prayers',file:'audio/Responsive_to_Prayers/track4.mid'},
        {name :'東方怪奇談',file:'audio/Responsive_to_Prayers/track5.mid'},
        {name :'天使伝説',file:'audio/Responsive_to_Prayers/track6.mid'},
        {name :'Oriental Magician',file:'audio/Responsive_to_Prayers/track7.mid'},
        {name :'破邪の小太刀',file:'audio/Responsive_to_Prayers/track8.mid'},
        {name :'魔鏡',file:'audio/Responsive_to_Prayers/track9.mid'},
        {name :'the Legend of KAGE',file:'audio/Responsive_to_Prayers/track10.mid'},
        {name :'いざ、倒れ逝くその時まで...',file:'audio/Responsive_to_Prayers/track11.mid'},
        {name :'死なばもろとも',file:'audio/Responsive_to_Prayers/track12.mid'},
        {name :'星幽剣士',file:'audio/Responsive_to_Prayers/track13.mid'},
        {name :'アイリス',file:'audio/Responsive_to_Prayers/track14.mid'},
        {name :'風の神社',file:'audio/Responsive_to_Prayers/unused.mid'},
    ],
    Eastern_Wonderland :[
        {name :'東方封魔録 ～ 浄土曼荼羅',file:'audio/Eastern_Wonderland/track1.mid'},
        {name :'博麗　～ Eastern Wind',file:'audio/Eastern_Wonderland/track2.mid'},
        {name :'She\'s in a temper!!',file:'audio/Eastern_Wonderland/track3.mid'},
        {name :'End of Daylight',file:'audio/Eastern_Wonderland/track4.mid'},
        {name :'やみのちから',file:'audio/Eastern_Wonderland/track5.mid'},
        {name :'幻夢界',file:'audio/Eastern_Wonderland/track6.mid'},
        {name :'死を賭して',file:'audio/Eastern_Wonderland/track7.mid'},
        {name :'ひもろぎ、むらさきにもえ',file:'audio/Eastern_Wonderland/track8.mid'},
        {name :'恋色マジック',file:'audio/Eastern_Wonderland/track9.mid'},
        {name :'東方封魔録　～ 幽幻乱舞',file:'audio/Eastern_Wonderland/track10.mid'},
        {name :'Complete Darkness',file:'audio/Eastern_Wonderland/track11.mid'},
        {name :'Extra Love',file:'audio/Eastern_Wonderland/track12.mid'},
        {name :'戦車娘がみるゆめ',file:'audio/Eastern_Wonderland/track13.mid'},
        {name :'遠野の森',file:'audio/Eastern_Wonderland/track14.mid'},
        {name :'昔話わんだーらんど',file:'audio/Eastern_Wonderland/track15.mid'},
        {name :'博麗神社境内',file:'audio/Eastern_Wonderland/unused1.mid'},
        {name :'陽落ちて',file:'audio/Eastern_Wonderland/unused2.mid'},
        {name :'封魔終演',file:'audio/Eastern_Wonderland/unused3.mid'},
    ],
    Dim_Dream :[
        {name:'夢は時空を越えて',file:'audio/Dim_Dream/track1.mid'},
        {name:'Selection',file:'audio/Dim_Dream/track2.mid'},
        {name:'東方妖恋談',file:'audio/Dim_Dream/track3.mid'},
        {name:'リーインカーネーション',file:'audio/Dim_Dream/track4.mid'},
        {name:'Dim. Dream',file:'audio/Dim_Dream/track5.mid'},
        {name:'Tabula rasa　～ 空白少女',file:'audio/Dim_Dream/track6.mid'},
        {name:'Maniacal Princess',file:'audio/Dim_Dream/track7.mid'},
        {name:'夢消失　～ Lost Dream',file:'audio/Dim_Dream/track8.mid'},
        {name:'夢幻遊戯　～ Dream War',file:'audio/Dim_Dream/track9.mid'},
        {name:'魔法決戦！　～ Fight it out!!',file:'audio/Dim_Dream/track10.mid'},
        {name:'Sailor of Time',file:'audio/Dim_Dream/track11.mid'},
        {name:'Strawberry Crisis!!',file:'audio/Dim_Dream/track12.mid'},
        {name:'非統一魔法世界論',file:'audio/Dim_Dream/track13.mid'},
        {name:'魔法鐘愛',file:'audio/Dim_Dream/track14.mid'},
        {name:'久遠の夢',file:'audio/Dim_Dream/track15.mid'},
        {name:'東方に青い空',file:'audio/Dim_Dream/track16.mid'},
        {name:'永遠の満月',file:'audio/Dim_Dream/track17.mid'},
        {name:'Maple Dream',file:'audio/Dim_Dream/track18.mid'},
        {name:'霊人の休日',file:'audio/Dim_Dream/track19.mid'},
        {name:'勝利デモ',file:'audio/Dim_Dream/track20.mid'},
        {name:'Game Over',file:'audio/Dim_Dream/track21.mid'},
        {name:'時の風',file:'audio/Dim_Dream/unused1.mid'},
        {name:'スターボウドリーム',file:'audio/Dim_Dream/unused2.mid'},
        {name:'Phantasmagoria',file:'audio/Dim_Dream/unused3.mid'},
    ],
    Lotus_Land_Story:[
        {name :'東方幻想郷　～ Lotus Land',file:'audio/Lotus_Land_Story/track1.mid'},
        {name :'Witching Dream',file:'audio/Lotus_Land_Story/track2.mid'},
        {name :'Selene\'s light',file:'audio/Lotus_Land_Story/track3.mid'},
        {name :'装飾戦　～ Decoration Battle',file:'audio/Lotus_Land_Story/track4.mid'},
        {name :'Break the Sabbath',file:'audio/Lotus_Land_Story/track5.mid'},
        {name :'紅響曲　～ Scarlet Phoneme',file:'audio/Lotus_Land_Story/track6.mid'},
        {name :'Bad Apple!!',file:'audio/Lotus_Land_Story/track7.mid'},
        {name :'霊戦　～ Perdition crisis',file:'audio/Lotus_Land_Story/track8.mid'},
        {name :'アリスマエステラ',file:'audio/Lotus_Land_Story/track9.mid'},
        {name :'少女綺想曲',file:'audio/Lotus_Land_Story/track10.mid'},
        {name :'星の器　～ Casket of Star',file:'audio/Lotus_Land_Story/track11.mid'},
        {name :'Lotus Love',file:'audio/Lotus_Land_Story/track12.mid'},
        {name :'眠れる恐怖　～ Sleeping Terror',file:'audio/Lotus_Land_Story/track13.mid'},
        {name :'Dream Land',file:'audio/Lotus_Land_Story/track14.mid'},
        {name :'幽夢　～ Inanimate Dream',file:'audio/Lotus_Land_Story/track15.mid'},
        {name :'禁じざるをえない遊戯',file:'audio/Lotus_Land_Story/track16.mid'},
        {name :'メイド夢幻　～ Icemilk Magic',file:'audio/Lotus_Land_Story/track17.mid'},
        {name :'かわいい悪魔　～ Innocence',file:'audio/Lotus_Land_Story/track18.mid'},
        {name :'Days',file:'audio/Lotus_Land_Story/track19.mid'},
        {name :'Peaceful',file:'audio/Lotus_Land_Story/track20.mid'},
        {name :'Arcadian Dream',file:'audio/Lotus_Land_Story/track21.mid'},
        {name :'幻想の住人',file:'audio/Lotus_Land_Story/track22.mid'},
        {name :'Lotus Road',file:'audio/Lotus_Land_Story/track23.mid'},
        {name :'Dreamy pilot',file:'audio/Lotus_Land_Story/track24.mid'},
        {name :'Incomplete Plot',file:'audio/Lotus_Land_Story/track25.mid'},
        {name :'Border Land',file:'audio/Lotus_Land_Story/track26.mid'},
        {name :'Magic Shop of Raspberry',file:'audio/Lotus_Land_Story/track27.mid'},
        {name :'Crescent Dream',file:'audio/Lotus_Land_Story/track28.mid'},
    ],
    Mystic_Square:[
        {name:'怪綺談　～ Mystic Square',file:'audio/Mystic_Square/track1.mid'},
        {name:'Dream Express',file:'audio/Mystic_Square/track2.mid'},
        {name:'魔法陣　～ Magic Square',file:'audio/Mystic_Square/track3.mid'},
        {name:'夢想時空',file:'audio/Mystic_Square/track4.mid'},
        {name:'霊天　～ Spiritual Heaven',file:'audio/Mystic_Square/track5.mid'},
        {name:'Romantic Children',file:'audio/Mystic_Square/track6.mid'},
        {name:'プラスチックマインド',file:'audio/Mystic_Square/track7.mid'},
        {name:'メイプルワイズ',file:'audio/Mystic_Square/track8.mid'},
        {name:'禁断の魔法　～ Forbidden Magic',file:'audio/Mystic_Square/track9.mid'},
        {name:'真紅の少女　～ Crimson Dead!!',file:'audio/Mystic_Square/track10.mid'},
        {name:'裏切りの少女　～ Judas Kiss',file:'audio/Mystic_Square/track11.mid'},
        {name:'the Last Judgement',file:'audio/Mystic_Square/track12.mid'},
        {name:'悲しき人形　～ Doll of Misery',file:'audio/Mystic_Square/track13.mid'},
        {name:'世界の果て　～ World\'s End',file:'audio/Mystic_Square/track14.mid'},
        {name:'神話幻想　～ Infinite Being',file:'audio/Mystic_Square/track15.mid'},
        {name:'不思議の国のアリス',file:'audio/Mystic_Square/track16.mid'},
        {name:'The Grimoire of Alice',file:'audio/Mystic_Square/track17.mid'},
        {name:'神社',file:'audio/Mystic_Square/track18.mid'},
        {name:'Endless',file:'audio/Mystic_Square/track19.mid'},
        {name:'久遠の楽園',file:'audio/Mystic_Square/track20.mid'},
        {name:'Mystic Dream',file:'audio/Mystic_Square/track21.mid'},
        {name:'Peaceful Romancer',file:'audio/Mystic_Square/track22.mid'},
        {name:'魂の休らむ所',file:'audio/Mystic_Square/track23.mid'},
    ],
    Flower_View:[],
};