const song_database = {
    Scarlet_Devil:[ //红魔乡
        { name: '赤より紅い夢', file: 'audio/Scarlet_Devil/title.mid' },
        { name: 'ほおずきみたいに紅い魂', file: 'audio/Scarlet_Devil/stage1_mid.mid' },
        { name: '妖魔夜行', file: 'audio/Scarlet_Devil/stage1_boss.mid' },
        { name: 'ルーネイトエルフ', file: 'audio/Scarlet_Devil/stage2_mid.mid' },
        { name: 'おてんば恋娘', file: 'audio/Scarlet_Devil/stage2_boss.mid' },
        { name: '上海紅茶館 ～ Chinese Tea', file: 'audio/Scarlet_Devil/stage3_mid.mid' },
        { name: '明治十七年の上海アリス', file: 'audio/Scarlet_Devil/stage3_boss.mid' },
        { name: 'ヴワル魔法図書館', file: 'audio/Scarlet_Devil/stage4_mid.mid' },
        { name: 'ラクトガール ～ 少女密室', file: 'audio/Scarlet_Devil/stage4_boss.mid' },
        { name: 'メイドと血の懐中時計', file: 'audio/Scarlet_Devil/stage5_mid.mid' },
        { name: '月時計 ～ ルナ・ダイアル', file: 'audio/Scarlet_Devil/stage5_boss.mid' },
        { name: 'ツェペシュの幼き末裔', file: 'audio/Scarlet_Devil/stage6_mid.mid' },
        { name: '亡き王女の為のセプテット', file: 'audio/Scarlet_Devil/stage6_boss.mid' },
        { name: '魔法少女達の百年祭', file: 'audio/Scarlet_Devil/stageEX_mid.mid' },
        { name: 'U.N.オーエンは彼女なのか？', file: 'audio/Scarlet_Devil/stageEX_boss.mid' },
        { name: '紅より儚い永遠', file: 'audio/Scarlet_Devil/ending.mid' },
        { name: '紅楼 ～ Eastern Dream...', file: 'audio/Scarlet_Devil/staff_roll.mid' }
    ],
    Perfect_Cherry: [  // 妖妖梦
        { name: '妖々夢 ～ Snow or Cherry', file: 'audio/Perfect_Cherry/title.mid' },
        { name: '無何有の郷 ～ Deep Mountain', file: 'audio/Perfect_Cherry/stage1_mid.mid' },
        { name: 'クリスタライズシルバー', file: 'audio/Perfect_Cherry/stage1_boss.mid' },
        { name: '遠野幻想物語', file: 'audio/Perfect_Cherry/stage2_mid.mid' },
        { name: 'ティアオイエツォン (withered leaf)', file: 'audio/Perfect_Cherry/stage2_boss.mid' },
        { name: 'ブクレシュティの人形師', file: 'audio/Perfect_Cherry/stage3_mid.mid' },
        { name: '人形裁判 ～ 人の形弄びし少女', file: 'audio/Perfect_Cherry/stage3_boss.mid' },
        { name: '天空の花の都', file: 'audio/Perfect_Cherry/stage4_mid.mid' },
        { name: '幽霊楽団 ～ Phantom Ensemble', file: 'audio/Perfect_Cherry/stage4_boss.mid' },
        { name: '東方妖々夢 ～ Ancient Temple', file: 'audio/Perfect_Cherry/stage5_mid.mid' },
        { name: '広有射怪鳥事 ～ Till When?', file: 'audio/Perfect_Cherry/stage5_boss.mid' },
        { name: 'アルティメットトゥルース', file: 'audio/Perfect_Cherry/stage6_mid.mid' },
        { name: '幽雅に咲かせ、墨染の桜 (Border of Life)', file: 'audio/Perfect_Cherry/stage6_bossA.mid' },
        { name: 'ボーダーオブライフ', file: 'audio/Perfect_Cherry/stage6_bossB.mid' },
        { name: '妖々跋扈', file: 'audio/Perfect_Cherry/stageEX_mid.mid' },
        { name: '少女幻葬 ～ Necro-Fantasy', file: 'audio/Perfect_Cherry/stageEX_boss.mid' },
        { name: '妖々跋扈 ～ Who done it!', file: 'audio/Perfect_Cherry/stagePH_mid.mid' },
        { name: 'ネクロファンタジア', file: 'audio/Perfect_Cherry/stagePH_boss.mid' },
        { name: '春風の夢', file: 'audio/Perfect_Cherry/ending.mid' },
        { name: 'さくらさくら ～ Japanize Dream...', file: 'audio/Perfect_Cherry/staff_roll.mid' }
    ],
    Imperishable_Night: [ // 永夜抄
        { name: '永夜抄 ～ Eastern Night', file: 'audio/Imperishable_Night/title.mid' },
        { name: '幻視の夜 ～ Ghostly Eyes', file: 'audio/Imperishable_Night/stage1_mid.mid' },
        { name: '蠢々秋月 ～ Mooned Insect',file:'audio/Imperishable_Night/stage1_boss.mid'},
        { name: '夜雀の歌声 ～ Night Bird',file:'audio/Imperishable_Night/stage2_mid.mid'},
        { name: 'もう歌しか聞こえない',file:'audio/Imperishable_Night/stage2_boss.mid'},
        { name: 'プレインエイジア',file:'audio/Imperishable_Night/stage3_boss.mid'},
        { name: '懐かしき東方の血 ～ Old World',file:'audio/Imperishable_Night/stage3_mid.mid'},
        { name: '永夜の報い ～ Imperishable Night',file:'audio/Imperishable_Night/stage4_mid.mid'},
        { name: '少女綺想曲 ～ Dream Battle',file:'audio/Imperishable_Night/stage4_boss_reimu.mid'},
        { name: '恋色マスタースパーク',file:'audio/Imperishable_Night/stage4_boss_marisa.mid'},
        { name: 'シンデレラケージ ～ Kagome-Kagome',file:'audio/Imperishable_Night/stage5_mid.mid'},
        { name: '狂気の瞳 ～ Invisible Full Moon',file:'audio/Imperishable_Night/stage5_boss.mid'},
        { name: 'ヴォヤージュ1969',file:'audio/Imperishable_Night/stage6_mid.mid'},
        { name: '千年幻想郷 ～ History of the Moon',file:'audio/Imperishable_Night/stage6A_boss.mid'},
        { name: '竹取飛翔 ～ Lunatic Princess', file: 'audio/Imperishable_Night/stage6B_boss.mid' },
        { name: 'ヴォヤージュ1970',file:'audio/Imperishable_Night/final_spell.mid'},
        { name:'エクステンドアッシュ ～ 蓬莱人',file:'audio/Imperishable_Night/stageEX_mid.mid'},
        { name:'月まで届け、不死の煙',file:'audio/Imperishable_Night/stageEX_boss.mid'},
        { name:'月見草',file:'audio/Imperishable_Night/ending.mid'},
        { name:'Eternal Dream ～ 幽玄の槭樹',file:'audio/Imperishable_Night/staff_roll.mid'},
        { name:'東方妖怪小町',file:'audio/Imperishable_Night/last_word.mid'}
    ]
};